### ISSUE TITLE
How to define categorical variable with different ranges?

### ISSUE THREAD

**Issue by TianningGao** [ma921/SOBER#1]
Assume I have a 4D categorical variable ranges in [[0,1], [0,1], [0,1,2,3,4], [0,1,2]], how should I define the categorical prior on this variable and pass into SOBER? As I know, each row in a torch.Tensor must has same dimesions.

**Comment by ma921** [comment]
Hi @TianningGao, I have just fixed the code to enable this.
You can now use the different number of categories, via setting;
categories = [[0,1], [0,1], [0,1,2,3,4], [0,1,2]]   # You can pass list of categories
prior = CategoricalPrior(categories)

Tutorial 2 is also updated to show this case (section 6).

**Comment by TianningGao** [comment]
Got it, thanks.
